### ISSUE TITLE
Violation of Font Awesome License Agreement

### ISSUE THREAD

**Issue by alexpoiry** [stechstudio/laravel-tiptap-demo-app#1]
Hello,

My name is Alex and I'm head of cybersecurity for Font Awesome.

It appears that you are hosting all our pro assets on your repository in a way that is publicly searchable. This violates the terms of our license agreement. I'd like to discuss options with you about how we might remedy this. I do not believe your primary intent is incorrect/illegal redistribution of our assets but that is effectively what is happening.

Please respond to this issue so we can discuss alternatives or make these assets private.

My preference is that we come to some mutually beneficial solution. As a company our goal isn't to make it difficult to use our product but there are some places where we do need to draw the line and giving away our entire product for free is one of those places. 

In general, I like to give people some time to respond and come up with a good solution. According to your main page it looks like you're in Asheville, NC, so it is possible that you're dealing with other far more serious issues at the moment. If so, don't feel compelled to respond immediately, I just want to bring this to your attention for the moment. I'll follow up periodically.

Please respond at your earliest convenience.

**Comment by jszobody** [comment]
Hi Alex. You're right, this was entirely a mistake on our part. We built this to show how we use the Tiptap HTML editor with a custom toolbar, and didn't mean to expose the pro assets to the world. My apologies. As soon as I hit send on this comment I'll make this repo private (or delete it entirely). 

If you want to discuss this any further I can be reached directly at jszobody@gmail.com (my Font Awesome licensed email).

As for being in Asheville, yes it's been a chaotic few weeks! I'm only just getting back online with solid internet.
